FROM golang:1.15-alpine

WORKDIR /root

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh && \
    apk add --no-cache autoconf automake libtool gettext gettext-dev make g++ texinfo curl && \
    go get github.com/go-delve/delve/cmd/dlv

WORKDIR /home/app/src
