// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 72999ebd2f
// Version Date: Wed Mar 17 08:36:51 UTC 2021

// Package grpc provides a gRPC client for the User service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "uas/user"
	"uas/user/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.UserServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var getuserinformationEndpoint endpoint.Endpoint
	{
		getuserinformationEndpoint = grpctransport.NewClient(
			conn,
			"user.User",
			"GetUserInformation",
			EncodeGRPCGetUserInformationRequest,
			DecodeGRPCGetUserInformationResponse,
			pb.GetUserInformationResponse{},
			clientOptions...,
		).Endpoint()
	}

	var createuserEndpoint endpoint.Endpoint
	{
		createuserEndpoint = grpctransport.NewClient(
			conn,
			"user.User",
			"CreateUser",
			EncodeGRPCCreateUserRequest,
			DecodeGRPCCreateUserResponse,
			pb.CreateUserResponse{},
			clientOptions...,
		).Endpoint()
	}

	var getalluserinformationEndpoint endpoint.Endpoint
	{
		getalluserinformationEndpoint = grpctransport.NewClient(
			conn,
			"user.User",
			"GetAllUserInformation",
			EncodeGRPCGetAllUserInformationRequest,
			DecodeGRPCGetAllUserInformationResponse,
			pb.GetAllUserInformationResponse{},
			clientOptions...,
		).Endpoint()
	}

	var getuserinformationemailEndpoint endpoint.Endpoint
	{
		getuserinformationemailEndpoint = grpctransport.NewClient(
			conn,
			"user.User",
			"GetUserInformationEmail",
			EncodeGRPCGetUserInformationEmailRequest,
			DecodeGRPCGetUserInformationEmailResponse,
			pb.GetUserInformationEmailResponse{},
			clientOptions...,
		).Endpoint()
	}

	var deleteuserEndpoint endpoint.Endpoint
	{
		deleteuserEndpoint = grpctransport.NewClient(
			conn,
			"user.User",
			"DeleteUser",
			EncodeGRPCDeleteUserRequest,
			DecodeGRPCDeleteUserResponse,
			pb.DeleteUserResponse{},
			clientOptions...,
		).Endpoint()
	}

	endpoints := svc.NewEndpoints()
	endpoints.GetUserInformationEndpoint = getuserinformationEndpoint
	endpoints.CreateUserEndpoint = createuserEndpoint
	endpoints.GetAllUserInformationEndpoint = getalluserinformationEndpoint
	endpoints.GetUserInformationEmailEndpoint = getuserinformationemailEndpoint
	endpoints.DeleteUserEndpoint = deleteuserEndpoint

	return endpoints, nil
}

// GRPC Client Decode

// DecodeGRPCGetUserInformationResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC getuserinformation reply to a user-domain getuserinformation response. Primarily useful in a client.
func DecodeGRPCGetUserInformationResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.GetUserInformationResponse)
	return reply, nil
}

// DecodeGRPCCreateUserResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC createuser reply to a user-domain createuser response. Primarily useful in a client.
func DecodeGRPCCreateUserResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.CreateUserResponse)
	return reply, nil
}

// DecodeGRPCGetAllUserInformationResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC getalluserinformation reply to a user-domain getalluserinformation response. Primarily useful in a client.
func DecodeGRPCGetAllUserInformationResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.GetAllUserInformationResponse)
	return reply, nil
}

// DecodeGRPCGetUserInformationEmailResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC getuserinformationemail reply to a user-domain getuserinformationemail response. Primarily useful in a client.
func DecodeGRPCGetUserInformationEmailResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.GetUserInformationEmailResponse)
	return reply, nil
}

// DecodeGRPCDeleteUserResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC deleteuser reply to a user-domain deleteuser response. Primarily useful in a client.
func DecodeGRPCDeleteUserResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.DeleteUserResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCGetUserInformationRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain getuserinformation request to a gRPC getuserinformation request. Primarily useful in a client.
func EncodeGRPCGetUserInformationRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.GetUserInformationRequest)
	return req, nil
}

// EncodeGRPCCreateUserRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain createuser request to a gRPC createuser request. Primarily useful in a client.
func EncodeGRPCCreateUserRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.CreateUserRequest)
	return req, nil
}

// EncodeGRPCGetAllUserInformationRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain getalluserinformation request to a gRPC getalluserinformation request. Primarily useful in a client.
func EncodeGRPCGetAllUserInformationRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.GetAllUserInformationRequest)
	return req, nil
}

// EncodeGRPCGetUserInformationEmailRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain getuserinformationemail request to a gRPC getuserinformationemail request. Primarily useful in a client.
func EncodeGRPCGetUserInformationEmailRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.GetUserInformationEmailRequest)
	return req, nil
}

// EncodeGRPCDeleteUserRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain deleteuser request to a gRPC deleteuser request. Primarily useful in a client.
func EncodeGRPCDeleteUserRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.DeleteUserRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
